### ISSUE TITLE
Can not summarize metrics for iSeq run

### ISSUE THREAD

**Issue by MatildaAslin** [Illumina/interop#182]
Hi! 

I'm having issues retrieving statistics from a publicly available iSeq dataset* 

*iSeq 100: 16S Metagenomics (ATCC Microbiome Standard MSA-1003) dataset 
https://basespace.illumina.com/run/72750678/16S-JHY027-120pM-2-phiX

I'm using your python example script with a few modifications, like printing the version of `interop` and adaptations to Python3:

```

"""
This example application displays the mean error rate averaged over all lanes for each read
"""


# @ [Reporting Summary Metrics in Python]

from interop import py_interop_run_metrics
from interop import py_interop_summary
from interop import py_interop_run
from interop import __version__ as interop_version
import numpy
import logging
import sys
import os


def main():
    """ Retrieve run folder paths from the command line
    Ensure only metrics required for summary are loaded
    Load the run metrics
    Calculate the summary metrics
    Display error by lane, read
    """
    logging.basicConfig(level=logging.INFO)
    logging.info("Using interop version: {}".format(interop_version))
    run_metrics = py_interop_run_metrics.run_metrics()
    summary = py_interop_summary.run_summary()
    valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
    py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load)

    for run_folder_path in sys.argv[1:]:
        run_folder = os.path.basename(run_folder_path)
        try:
            run_metrics.read(run_folder_path, valid_to_load)
        except Exception as ex:
            logging.warn("Skipping - cannot read RunInfo.xml: %s - %s"%(run_folder, str(ex)))
            continue
        py_interop_summary.summarize_run_metrics(run_metrics, summary)
        error_rate_read_lane_surface = numpy.zeros((summary.size(), summary.lane_count(), summary.surface_count()))
        for read_index in range(summary.size()):
            for lane_index in range(summary.lane_count()):
                for surface_index in range(summary.surface_count()):
                    error_rate_read_lane_surface[read_index, lane_index, surface_index] = \
                        summary.at(read_index).at(lane_index).at(surface_index).error_rate().mean()
        logging.info("Run Folder: "+run_folder)
        for read_index in range(summary.size()):
            read_summary = summary.at(read_index)
            print(read_summary)
            logging.info("Read "+str(read_summary.read().number())+" - Top Surface Mean Error: "+str(error_rate_read_lane_surface[read_index, :, 0].mean()))

if __name__ == '__main__':
    main()

```

When running the above script on the iSeq data I get the following error: 
```
INFO:root:Using interop version: 1.1.4
Traceback (most recent call last):
  File "example_summary.py", line 54, in <module>
    main()
  File "example_summary.py", line 40, in main
    py_interop_summary.summarize_run_metrics(run_metrics, summary)
interop.py_interop_run_metrics.invalid_channel_exception: Invalid channel names: 1,2
/io/./interop/logic/utils/channel.h::expected_order (112)

```

The script works fine on a MiSeq run.

**Comment by nudpa** [comment]
Hello @MatildaAslin, thanks for catching this! We will put out a fix for this soon.

**Comment by ezralanglois** [comment]
Hi Johan,

We just released the latest version, which should include the changes in #183. Everything but the MacOSX Build. We will need to put another another release to fix the scripts used to package that build.

Best,
Rob

**Comment by ezralanglois** [comment]
1.1.6 is just released and supports Linux, MacOSX and Windows

**Comment by johandahlberg** [comment]
That's great! Thanks.
