### ISSUE TITLE
Bad Format Exception for NextSeq2000

### ISSUE THREAD

**Issue by paulwolk** [Illumina/interop#223]
With the latest InterOp-Version 1.1.10 I try to process the (unchanged) InterOp-Files of a NextSeq2000-Run. Everything works totally fine, except for the ErrorMetricsOut.bin, when I exclude this passage from the script, there is no problem anymore. What could be the error here, what does this mean?

```
Traceback (most recent call last):
  File "readBinToCsv.py", line 40, in <module>
    run_metrics_read = run_metrics.read(run_folder, valid_to_load)
  File "/x/y/.local/lib/python3.5/site-packages/interop/py_interop_run_metrics.py", line 391, in read
    return _py_interop_run_metrics.run_metrics_read(self, *args)
interop.py_interop_comm.bad_format_exception: No format found to parse ErrorMetricsOut.bin with version: 5 of 2 /io/./interop/io/metric_stream.h::read_metrics (111)
```

Best
Paul

**Comment by ezralanglois** [comment]
I just put a PR out to fix this issue and expose the new metric format.

**Comment by DavidStreid** [comment]
I am still receiving this error w/ version 1.1.11. I have also tried with 1.1.23. This is only happening w/ a NextSeq 1000/2000 run w/ python v2.7.
Do you have any suggestions for how to resolve this? Thank you

CODE
```
from interop import py_interop_run, py_interop_table
from interop import py_interop_run_metrics
from interop import py_interop_summary
...
run_folder_path="/MY/PATH"
valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load)
run_metrics.read(run_folder_path, valid_to_load)
```

ERROR
```
Traceback (most recent call last):
  File "run_interop_parser.py", line 150, in <module>
    data = parse_runs(files)
  File "run_interop_parser.py", line 66, in parse_runs
    json = parse_single_json(run_folder_path)
  File "run_interop_parser.py", line 29, in parse_single_json
    run_metrics.read(run_folder_path, valid_to_load)
  File "/home/upops/interop/venv/lib/python3.4/site-packages/interop/py_interop_run_metrics.py", line 391, in read
    return _py_interop_run_metrics.run_metrics_read(self, *args)
interop.py_interop_comm.bad_format_exception: No format found to parse ErrorMetricsOut.bin with version: 5 of 2
/io/./interop/io/metric_stream.h::read_metrics (111)
(venv)-bash-4.2$ pip list | grep interop
You are using pip version 7.1.0, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
interop (1.1.11)
```

**Comment by ezralanglois** [comment]
The error
```
interop.py_interop_comm.bad_format_exception: No format found to parse ErrorMetricsOut.bin with version: 5 of 2
```
means that the version of interop is too old. I would expect this error from `1.1.11`; however, you should not get this for 1.1.23.

I tried this on my Mac, and it loaded fine.

Can you produced this with 1.1.23 and also print the version of interop?
```
import interop
print(interop.__version__)
```

I suspect it did not upgrade.

**Comment by DavidStreid** [comment]
Thank you for your help. You're right - the python version running the script is v3.4, which only has interops v1.1.8 installed. My issue is resolved
