### ISSUE TITLE
interop.py_interop_metrics.index_out_of_bounds_exception: error with indexing metrics (Novaseq)

### ISSUE THREAD

**Issue by yelekley** [Illumina/interop#230]
Hello,
I'm trying to indexing matrix. The following code works for Hiseq but not for Novaseq run. Please suggest a fix. Thanks
Error message:
```
this many lanes: 4
Traceback (most recent call last):
  File "interopTst.py", line 31, in <module>
    lane_summary = summary.at(lane)
  File "/usr/lib64/python2.7/site-packages/interop/py_interop_summary.py", line 958, in at
    return _py_interop_summary.index_flowcell_summary_at(self, n)
interop.py_interop_metrics.index_out_of_bounds_exception: Lane index exceeds lane count - 0 >= 0
/io/./interop/model/summary/index_flowcell_summary.h::operator[] (63)

```
```
import pandas as pd
from collections import OrderedDict
from interop import py_interop_run_metrics, py_interop_run, py_interop_summary
import os
import numpy as np

run_folder = "/path/to/run/folder"
run_metrics = py_interop_run_metrics.run_metrics()
valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
py_interop_run_metrics.list_index_metrics_to_load(valid_to_load)
run_folder = run_metrics.read(run_folder, valid_to_load)
summary = py_interop_summary.index_flowcell_summary()
py_interop_summary.summarize_index_metrics(run_metrics, summary)
summary_lane = py_interop_summary.run_summary()
py_interop_summary.summarize_run_metrics(run_metrics, summary_lane)
lanes = summary_lane.lane_count()
print("this many lanes: " + str(lanes))

for lane in range(lanes):
    columns = (('sample_id', 'sample_id'), ('index1', 'index1'), ('index2', 'index2'), ('fraction_mapped', 'fraction_mapped'), ('cluster_count', 'cluster_count'))
    lane_summary = summary.at(lane)
    d = []
    for label, func in columns:
        d.append( (label, pd.Series([getattr(lane_summary.at(i), func)() for i in range(lane_summary.size())], index=[lane_summary.at(i).id() for i in range(lane_summary.size())])))
        df = pd.DataFrame.from_items(d)
        df
        print(df) 
```

**Comment by ezralanglois** [comment]
Is IndexMetricsOut.bin present in the NovaSeq run?

One way to check would be to add
```assert(run_folder.index_metric_set().size()>0)
```
after
```
run_folder = run_metrics.read(run_folder, valid_to_load)
```

**Comment by yelekley** [comment]
No, 'IndexMetricsOut.bin' is not in 'InterOp'. Do you know why? Thanks

**Comment by yelekley** [comment]
Is this standard for Novaseq? Any solution to this issue? Thanks

**Comment by yelekley** [comment]
Just check a Nextseq run and it's not there either. :( Any workarounds? Thanks

**Comment by ezralanglois** [comment]
IndexMetricsOut.bin is not produced by RTA, but rather by bcl2fastq or not by bcl-convert (the replacement for bcl2fastq). You would have to download the IndexMetricsOut.bin from the FastQ project in BaseSpace and copy it into the InterOp folder.

**Comment by yelekley** [comment]
Thank you, bcl-converter also works?
Is there an easy way to calculate the number of Undetermined clusters per lane?
Thanks

**Comment by ezralanglois** [comment]
The fraction mapped is the % demux. 100% minus that times PF cluster count will give that.

**Comment by yelekley** [comment]
Thanks, do you have stdev function available for PctClustersPF?

**Comment by ezralanglois** [comment]
Not for the index summary.

**Comment by yelekley** [comment]
Ok thanks, how to get it for metrics summary
     ```
   run_metrics = py_interop_run_metrics.run_metrics()
    valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
    py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load)
    rfolder = run_metrics.read(rfolder, valid_to_load)
    summary = py_interop_summary.run_summary()
    lanes = summary.lane_count()
    reads = get_non_index_reads(summary)
    for lane in range(lanes):
            print "the lane is:", (lane + 1)
            for new_read_nbr, original_read_nbr in enumerate(reads):
                read = summary.at(original_read_nbr).at(lane)
                read.?
                
```

**Comment by yelekley** [comment]
Would like to get stdevClusterCountRaw and stdevPctClustersPF for read level, if possible. Thanks

**Comment by ezralanglois** [comment]
We don't support this in the summary logic on the run or read level.

You can populate the the imaging table as shown here:
https://github.com/Illumina/interop/issues/221

And calculate those files there by selecting each read.
