### ISSUE TITLE
question about install

### ISSUE THREAD

**Issue by vthovarai** [Illumina/interop#244]
Hello!
I've been trying to install the InterOp Library and I seem to have run into some issues. 
I have independently tried both the PyPI package as well downloading and specifying the wheel file:

pip3 install interop
pip3 install interop-1.1.16-cp37-cp37m-macosx_10_15_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl 

The install itself seems to work fine but I get the following error on testing:

python3 -m interop --test

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/interop/py_interop_run.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/interop/_py_interop_run.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/interop/_py_interop_run.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/interop/_py_interop_run.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/interop/__main__.py", line 4, in <module>
    from interop import py_interop_run,py_interop_metrics,py_interop_run_metrics,py_interop_comm,py_interop_table,py_interop_plot,py_interop_summary
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/interop/py_interop_run.py", line 17, in <module>
    _py_interop_run = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/interop/py_interop_run.py", line 16, in swig_import_helper
    return importlib.import_module('_py_interop_run')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_py_interop_run'

Before I go the more involved way of building from source; I wanted to check if you may have some obvious tips/suggestions for me that I may be missing.
Thanks in advance!
Vishal

**Comment by ezralanglois** [comment]
Hi Vishal,

This might be due to the upgrade of the mac osx agent. We can downgrade it on the next release and see if that helps.

For now, try installing an older version, like 1.1.15

**Comment by ezralanglois** [comment]
I have a PR out that will automatically close this ticket when this is fixed for `1.1.17`

**Comment by ezralanglois** [comment]
There is no difference between 1.1.5 and 1.1.6 for the Python wheel

**Comment by vthovarai** [comment]
Hi Ezra,
Thanks for your prompt response!
I was able to install and successfully test 1.1.5
Vishal
