### ISSUE TITLE
interop.py_interop_comm.incomplete_file_exception for runs with no indices/demultiplexing

### ISSUE THREAD

**Issue by nicolazilio** [Illumina/interop#341]
Hello there,

It appears that I can't open InterOp folders for runs where no demultiplexing occured, that is, where no indices were provided in the sample sheet

```
Traceback (most recent call last):
  File "/opt/pushParkourStats.py", line 112, in pushRunStats
    interop.read(
  File "/opt/conda/lib/python3.10/site-packages/interop/core.py", line 819, in read
    run_metrics = read_metric(filename, run_metrics=run_metrics, finalize=True)
  File "/opt/conda/lib/python3.10/site-packages/interop/core.py", line 849, in read_metric
    run_metrics.read_metrics_from_buffer(metric_group, data)
  File "/opt/conda/lib/python3.10/site-packages/interop/py_interop_run_metrics.py", line 334, in read_metrics_from_buffer
    return _py_interop_run_metrics.run_metrics_read_metrics_from_buffer(self, group, buffer)
interop.py_interop_comm.incomplete_file_exception: Insufficient data read from the file, got: 0 != expected: 9 for Index  v2
/io/./interop/io/format/metric_format.h::test_stream (250)
```

The offending line is [this one](https://github.com/imbforge/parkour2/blob/4d5b40c744f5dc60704e702ea7368f0723dcedf3/misc/pushParkourStats/pushParkourStats.py#L111).

I can provide you with an example, via DM.

**Comment by ezralanglois** [comment]
Incomplete file exception does not mean nothing was parsed. We normally catch and ignore this exception except when we expect the run to be complete.
